### ISSUE TITLE
Update: Link to Data Collection on HuBMAP Portal

### ISSUE THREAD

**Issue by emquardokus** [juyingnan/vccf_visualization#8]
@juyingnan @katyb
I was reviewing materials for flagship papers and noticed on the companion website https://hubmapconsortium.github.io/vccf-visualization-2022/ there was a missing link for 
“Link to Data Collection on HuBMAP Portal"

A link now exists on the HuBMAP data portal collections with this link:
https://portal.hubmapconsortium.org/browse/collection/34b068d4a926f77fd98b3d968b6c172f

**Comment by juyingnan** [comment]
> @juyingnan @katyb I was reviewing materials for flagship papers and noticed on the companion website https://hubmapconsortium.github.io/vccf-visualization-2022/ there was a missing link for “Link to Data Collection on HuBMAP Portal"
> 
> A link now exists on the HuBMAP data portal collections with this link: https://portal.hubmapconsortium.org/browse/collection/34b068d4a926f77fd98b3d968b6c172f

Thank you very much. The link has been updated.
